baseURL = "https://zerodemy.com/"
title = "Zerodemy Lyrics"
languageCode = "bn-BD"
DefaultContentLanguage = "bn"
defaultContentLanguage = "bn"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

paginate = 10

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
subtitle = "Collection of Bengali Lyrics"
subtitle_bn = "বাংলা লিরিক্সের সংগ্রহশালা"
title_bn = "জিরোডেমি লিরিক্স"
site_logo = "https://books.zerodemy.com/images/logo temporary.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
