baseURL = "https://zerodemy.com"
languageCode = "bn-BD"
DefaultContentLanguage = "bn"
defaultContentLanguage = "bn"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[outputs]
  home = [ "HTML", "RSS", "JSON"]